/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Model.ComboCurso;
import Model.GestorAsistencia;
import Model.GestorCurso;
import Model.GestorInscripcion;
import Model.VMCertificado;
import Model.VMInscriptosPagados;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernando M. de Lima
 */
public class MostrarInscriptosParaComprobante extends javax.swing.JFrame {

    /**
     * Creates new form Mostrar
     */
    public MostrarInscriptosParaComprobante() {
        initComponents();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInscriptos = new javax.swing.JTable();
        cmbCursos = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        btnGenerarComprobante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblInscriptos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblInscriptos);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnGenerarComprobante.setText("Genenarar comprobante");
        btnGenerarComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarComprobanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 702, Short.MAX_VALUE)
                        .addComponent(btnActualizar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGenerarComprobante)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarComprobante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        if (cmbCursos.getSelectedIndex() != -1) {
            int idCurso = ((ComboCurso) cmbCursos.getSelectedItem()).getId();
            GestorInscripcion gi = new GestorInscripcion();
            ArrayList<VMInscriptosPagados> lista = gi.obtenerPorCursoPagados(idCurso);
            Object[] columnas = {"Codigo", "Nombre", "Pago"};
            model.setColumnIdentifiers(columnas);
            for (VMInscriptosPagados vm : lista) {
                Object[] fila = {vm.getCodigo(), vm.getNombre(), vm.getPago()};
                model.addRow(fila);
            }
        }
        tblInscriptos.setModel(model);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGenerarComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarComprobanteActionPerformed
        // TODO add your handling code here:
        if (cmbCursos.getSelectedIndex() <= 0) {
            if (tblInscriptos.getModel().getValueAt(tblInscriptos.getSelectedRow(), 2).equals("Pago completo")) {
                int idInscripcion = (int) tblInscriptos.getModel().getValueAt(tblInscriptos.getSelectedRow(), 0);
                GestorAsistencia ga = new GestorAsistencia();
                VMCertificado vmc = ga.ObtenerCertificadoPorIdInscripcion(idInscripcion);
                imprimirPDF(vmc);
            } else {
                JOptionPane.showMessageDialog(null, "No se puede realizar el certificado para este inscripto porque no cumple las condiciones");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado un inscripto");
        }
    }//GEN-LAST:event_btnGenerarComprobanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarInscriptosParaComprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarInscriptosParaComprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarInscriptosParaComprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarInscriptosParaComprobante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarInscriptosParaComprobante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnGenerarComprobante;
    private javax.swing.JComboBox<String> cmbCursos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInscriptos;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        try {
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            GestorCurso gc = new GestorCurso();
            ArrayList<ComboCurso> lista = gc.ComboCursosActuales();
            for (ComboCurso comboCurso : lista) {
                model.addElement(comboCurso);
            }
            cmbCursos.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(MostrarInscriptosParaComprobante.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MostrarInscriptosParaComprobante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void imprimirPDF(VMCertificado vmc) {
        try {
            Document doc = new Document(PageSize.A4.rotate());
            PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream("Certificado" + vmc.getAlumno().replace(", ", "") + ".pdf"));

            doc.open();

//            //seteamos el titulo
//            Font letraTitulo = FontFactory.getFont("Verdana", 24, Font.UNDERLINE);
//            Paragraph title = new Paragraph("Certificado", letraTitulo);
//            title.setAlignment(Element.ALIGN_CENTER);
            //seteamos la imagen de certificado que utilizaremos
            com.itextpdf.text.Image certificado = com.itextpdf.text.Image.getInstance("src/Imagenes/certificado.jpg");
            float width = doc.getPageSize().getWidth();
            float height = doc.getPageSize().getHeight();
            writer.getDirectContentUnder().addImage(certificado, width, 0, 0, height, 0, 0);

            //seteamos el contenido del mensaje
            Font letraContenido = FontFactory.getFont(FontFactory.TIMES_ROMAN, 20, Font.ITALIC);
            Paragraph contenido = new Paragraph("  ", letraContenido);
            Paragraph contenido1 = new Paragraph("Se hace constar que el alumno " + vmc.getAlumno() + ", \ncon Documento Nro: " + vmc.getDocumento() + "\n Asistió y aprobó el curso " + vmc.getNombreCurso(), letraContenido);
            contenido1.setIndentationLeft(90);
            contenido1.setSpacingBefore(120);

            //seteamos el contenido del mensaje
            Font letraContenido2 = FontFactory.getFont(FontFactory.TIMES_ROMAN, 20, Font.ITALIC);
            Paragraph contenido2 = new Paragraph("con una duración de " + vmc.getHoras() + " horas.  \n desde: " + vmc.getFechaInicio() + " hasta: " + vmc.getFechaFinal(), letraContenido2);
            contenido2.setIndentationLeft(0);
            contenido2.setSpacingBefore(70);
            contenido2.setAlignment(Element.ALIGN_CENTER);

            //pasamos al documento (por orden) las cosas que deseamos mostrar
            doc.add(contenido);
            doc.add(contenido1);
            doc.add(contenido2);

            doc.close();

            Desktop.getDesktop().open(new File("Certificado" + vmc.getAlumno().replace(", ", "") + ".pdf"));
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        } catch (DocumentException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }
}
