/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Model.ComboCurso;
import Model.ComboNuevoCursante;
import Model.DatosGenerales;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import Model.GestorCurso;
import Model.GestorInscripcion;
import Model.GestorTipoDni;
import Model.TipoDni;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 *
 * @author Yasmin
 */
public class RegistrarInscripto extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarInscripto
     */
    private int instancia;
    GestorCurso g;
    final JDialog dialog = new JDialog();
        
    
    public RegistrarInscripto() {
        initComponents();
        cargaCmb();
        cargarDiaCombo();
        this.setLocationRelativeTo(null);
        dialog.setAlwaysOnTop(true);
    }
    
    public RegistrarInscripto (int x) {
        initComponents();
        cargaCmb();
        cargarDiaCombo();
        g = new GestorCurso();
        GestorTipoDni gtd = new GestorTipoDni();
        try {            
            cargarComboCurso(g.ComboCursosNegro());// CAMBIAR
            cargarComboTipoDni(gtd.obtenerTodos());
        } catch (SQLException ex) {
        } catch (ClassNotFoundException ex) {
        }
        this.setLocationRelativeTo(null);
        
        instancia = x;
        switch (instancia){
            case 1://matriculado
                txtLegajo.setEnabled(true);
                txtProfecion.setEnabled(false);
                txtNombre.setEnabled(false);
                txtApellido.setEnabled(false);
                txtDocumento.setEnabled(false);
                cmbTipoDocumento.setEnabled(false);
                cmbAnio.setEnabled(false);
                cmbDia.setEnabled(false);
                cmbMes.setEnabled(false);
                txtMail.setEnabled(false);
                txtTelefono.setEnabled(false);
                break;
            case 2://Familiar
                txtProfecion.setEnabled(false);
                txtLegajo.setEnabled(true);
                break;
            case 3://Otro
                txtProfecion.setEnabled(false);
                txtLegajo.setEnabled(false);
                break;
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbMes = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cmbAnio = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        cmbCursos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCarcgar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtProfecion = new javax.swing.JTextField();
        cmbDia = new javax.swing.JComboBox();
        txtApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtLegajo = new javax.swing.JTextField();
        cmbTipoDocumento = new javax.swing.JComboBox<>();
        btnNuevoMAtriculado = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Inscripción");
        setAlwaysOnTop(true);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(680, 280));
        setPreferredSize(new java.awt.Dimension(680, 280));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        cmbMes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesActionPerformed(evt);
            }
        });
        getContentPane().add(cmbMes);
        cmbMes.setBounds(540, 90, 50, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("E-Mail");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 140, 50, 17);

        cmbAnio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAnioActionPerformed(evt);
            }
        });
        getContentPane().add(cmbAnio);
        cmbAnio.setBounds(460, 90, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 60, 55, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Curso");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 20, 38, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("/");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 100, 7, 17);

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(80, 173, 240, 30);

        cmbCursos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cmbCursos);
        cmbCursos.setBounds(260, 13, 400, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Apellido");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 60, 50, 17);

        txtDocumento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtDocumento);
        txtDocumento.setBounds(160, 93, 150, 30);

        txtMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtMail);
        txtMail.setBounds(80, 130, 580, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Documento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 100, 73, 17);

        btnCarcgar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCarcgar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arrow.png"))); // NOI18N
        btnCarcgar.setText("Cargar");
        btnCarcgar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarcgarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarcgar);
        btnCarcgar.setBounds(560, 215, 93, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Profesión");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(330, 180, 56, 17);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtNombre);
        txtNombre.setBounds(80, 53, 230, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 100, 126, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Legajo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 20, 55, 17);

        txtProfecion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtProfecion);
        txtProfecion.setBounds(400, 173, 260, 30);

        cmbDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cmbDia);
        cmbDia.setBounds(610, 90, 50, 30);

        txtApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtApellido);
        txtApellido.setBounds(383, 53, 280, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Teléfono");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 180, 52, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("/");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(600, 100, 7, 17);

        txtLegajo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtLegajo);
        txtLegajo.setBounds(80, 13, 110, 30);

        cmbTipoDocumento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cmbTipoDocumento);
        cmbTipoDocumento.setBounds(90, 90, 65, 30);

        btnNuevoMAtriculado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevoMAtriculado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addMatriculado.png"))); // NOI18N
        btnNuevoMAtriculado.setText("Nuevo");
        btnNuevoMAtriculado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoMAtriculadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoMAtriculado);
        btnNuevoMAtriculado.setBounds(440, 215, 100, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRegistrar.jpg"))); // NOI18N
        jLabel11.setText("jLabel1");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-110, 0, 300, 430);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRegistrar.jpg"))); // NOI18N
        jLabel13.setText("jLabel1");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(180, 0, 500, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarcgarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarcgarActionPerformed
        GestorInscripcion gi = new GestorInscripcion();
        switch (instancia){
            case 1://matriculado
                if (esValidoM()){
                    try {
                        gi.agregarInscripcionMatriculado(Integer.parseInt(txtLegajo.getText()), ((ComboCurso)cmbCursos.getSelectedItem()).getId());
                        JOptionPane.showMessageDialog(dialog, "Se ha insertado un nuevo registro");
                        limpiarControles();
                    } catch (ClassNotFoundException ex) {
                        System.out.println(ex);
                    }
                }
            break;
            case 2://Familiar
                if (esValidoF()){
                    try {
                        DatosGenerales dg = new DatosGenerales();
                        dg.setNombre(txtNombre.getText());
                        dg.setApellido(txtApellido.getText());
                        dg.setTipoDni(((TipoDni)cmbTipoDocumento.getSelectedItem()).getId());
                        dg.setDni(Integer.parseInt(txtDocumento.getText()));
                        dg.setFechaNacimiento(cmbAnio.getSelectedItem().toString() + "/" + cmbMes.getSelectedItem().toString() + "/" + cmbDia.getSelectedItem().toString());
                        dg.setEmail(txtMail.getText());
                        dg.setTelefono(txtTelefono.getText());
                        gi.agregarInscripcionFamiliar(dg, Integer.parseInt(txtLegajo.getText()), ((ComboCurso)cmbCursos.getSelectedItem()).getId());
                        JOptionPane.showMessageDialog(dialog, "Se ha insertado un nuevo registro");
                        limpiarControles();
                    } catch (ClassNotFoundException ex) {
                    } catch (SQLException ex) {
                    }
                }
            break;
            case 3://Otro
                if (esValidoO()){
                    try {
                        DatosGenerales dg = new DatosGenerales();
                        dg.setNombre(txtNombre.getText());
                        dg.setApellido(txtApellido.getText());
                        dg.setTipoDni(((TipoDni)cmbTipoDocumento.getSelectedItem()).getId());
                        dg.setDni(Integer.parseInt(txtDocumento.getText()));
                        dg.setFechaNacimiento(cmbAnio.getSelectedItem().toString() + "/" + cmbMes.getSelectedItem().toString() + "/" + cmbDia.getSelectedItem().toString());
                        dg.setEmail(txtMail.getText());
                        dg.setTelefono(txtTelefono.getText());
                        gi.agregarInscripcionOtro(dg, ((ComboCurso)cmbCursos.getSelectedItem()).getId());
                        JOptionPane.showMessageDialog(dialog, "Se ha insertado un nuevo registro");
                        limpiarControles();
                    } catch (ClassNotFoundException ex) {
                    }
                }
            break;
        }
    }//GEN-LAST:event_btnCarcgarActionPerformed

    private void cmbAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAnioActionPerformed
        cargarDiaCombo();
    }//GEN-LAST:event_cmbAnioActionPerformed

    private void cmbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesActionPerformed
        cargarDiaCombo();
    }//GEN-LAST:event_cmbMesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        MenuPrincipal.vRegistrarInscripcion = false;
    }//GEN-LAST:event_formWindowClosing

    private void btnNuevoMAtriculadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoMAtriculadoActionPerformed
        if (MenuPrincipal.vRegistrarMatriculado == false) {
            MenuPrincipal.vRegistrarMatriculado = true;
            RegistrarMatriculado rm;
            try {
                rm = new RegistrarMatriculado();
                rm.setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnNuevoMAtriculadoActionPerformed

    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/IconoDefinitivo.jpg"));
        return retValue;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarInscripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarInscripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarInscripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarInscripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarInscripto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarcgar;
    private javax.swing.JButton btnNuevoMAtriculado;
    private javax.swing.JComboBox cmbAnio;
    private javax.swing.JComboBox<String> cmbCursos;
    private javax.swing.JComboBox cmbDia;
    private javax.swing.JComboBox cmbMes;
    private javax.swing.JComboBox<String> cmbTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtLegajo;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtProfecion;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
    
    
    private void cargaCmb() {
        DefaultComboBoxModel modelAnio = new DefaultComboBoxModel();
        DefaultComboBoxModel modelMes = new DefaultComboBoxModel();
        
        int anio = 1900;
        int mes = 1;
 
        Calendar cal= Calendar.getInstance(); 
        int year = cal.get(Calendar.YEAR); 
        
        while (anio <= year) {            
            modelAnio.addElement(anio);
            anio++;
        }
        cmbAnio.setModel(modelAnio);
        
        while (mes <= 12) {            
            modelMes.addElement(mes);
            mes++;
        }
        cmbMes.setModel(modelMes);
        
    }

    private void cargarDiaCombo() {
        DefaultComboBoxModel modelDia = new DefaultComboBoxModel();
        int dia = 1;
        int mes = cmbMes.getSelectedIndex()+1;

        while (dia <= 28) {            
            modelDia.addElement(dia);
            dia++;
        } 
        
        if(mes == 2){
            if((int)cmbAnio.getSelectedItem()%4 == 0 && ((int)cmbAnio.getSelectedItem()%100 != 0 || (int)cmbAnio.getSelectedItem()%400 == 0)){
                modelDia.addElement(dia);
            }
        }else if(mes==1 || mes==3 || mes==5 || mes==7 || mes==8 || mes==10 || mes==12){
            while (dia <= 31) {            
                modelDia.addElement(dia);
                dia++;
            }
        }else{
            while (dia <= 30) {            
                modelDia.addElement(dia);
                dia++;
            }
        }
        cmbDia.setModel(modelDia);
    }
    
    public void cargarComboCurso(ArrayList listaGenerica)
    {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        for (Object elemento : listaGenerica) {
            model.addElement(elemento);
        }
        
        cmbCursos.setModel(model);
    }

    private boolean esValidoM() {
        try {
            Integer.parseInt(txtLegajo.getText());
        }catch (Exception ex){
            JOptionPane.showMessageDialog(dialog, "El legajo debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
            return false;            
        }
        if (cmbCursos.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(dialog, "¡Seleccione un curso!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;            
        }
        return true;
    }

    private boolean esValidoF() {
        try{
            Integer.parseInt(txtDocumento.getText());
        }catch (Exception ex){
            JOptionPane.showMessageDialog(dialog, "El documento debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        try{
            Integer.parseInt(txtLegajo.getText());
        }catch (Exception ex){
            JOptionPane.showMessageDialog(dialog, "El legajo debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(dialog, "El campo nombre no debe estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txtApellido.getText().isEmpty()){
            JOptionPane.showMessageDialog(dialog, "El campo apellido no debe estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txtMail.getText().isEmpty()){
            JOptionPane.showMessageDialog(dialog, "El campo mail no debe estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txtTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(dialog, "El campo telefono no debe estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (cmbTipoDocumento.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(dialog, "¡Seleccione un tipo de documento!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (cmbCursos.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(dialog, "¡Seleccione un curso!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean esValidoO() {
        try{
            Integer.parseInt(txtDocumento.getText());
        }catch (Exception ex){
            JOptionPane.showMessageDialog(dialog, "El documento debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(dialog, "El campo nombre no debe estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txtApellido.getText().isEmpty()){
            JOptionPane.showMessageDialog(dialog, "El campo apellido no debe estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txtMail.getText().isEmpty()){
            JOptionPane.showMessageDialog(dialog, "El campo mail no debe estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (txtTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(dialog, "El campo telefono no debe estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (cmbTipoDocumento.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(dialog, "¡Seleccione un tipo de documento!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (cmbCursos.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(dialog, "¡Seleccione un curso!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void cargarComboTipoDni(ArrayList<TipoDni> obtenerTodos) {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        for (Object elemento : obtenerTodos) {
            model.addElement(elemento);
        }
        
        cmbTipoDocumento.setModel(model);
    }

    private void limpiarControles() {
        txtApellido.setText("");
        txtDocumento.setText("");
        txtLegajo.setText("");
        txtMail.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        cmbTipoDocumento.setSelectedIndex(-1);
        cmbCursos.setSelectedIndex(-1);
        cmbAnio.setSelectedIndex(0);
        cmbMes.setSelectedIndex(0);
        cmbDia.setSelectedIndex(0);
    }
}
